name: moot
favicon: null
layout_spectrum: 0.3165746424347162
typography_spectrum: 0.9331556418910623
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5609668823890388
  lightness: 0.6614719540812075
  saturation: 0.17042006948031485
  rhythmicContrast: 0.08923195931129158
purpose: []
